In [46]:
#Loading the dataset:

import pandas as pd

df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.9 MB

In [48]:
#"TotalCharges" was stored in text so converted that using(to_numeric)

df["TotalCharges"] = pd.to_numeric(df["TotalCharges"],errors= 'coerce')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.8 MB

In [49]:
# Missing values in that column:

df["TotalCharges"].isnull().sum()

np.int64(11)

In [50]:
# isnull() gives true/false per row:

df[df["TotalCharges"].isnull()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [51]:
# Blank rows were filled with zero(0).

df["TotalCharges"] = df["TotalCharges"].fillna(0)

In [52]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [53]:
# Have counted the churn in percentage using normalize.

df["Churn"].value_counts(normalize=True) * 100

Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

In [54]:
#No use of 'customerID' so dropped that column.

df = df.drop('customerID', axis = 1)
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [55]:
# Converted 'Churn' into yes/no into 0 & 1 using map.

cols = ['Churn']
for col in cols:
    df['Churn'] = df['Churn'].map({'Yes': 1, 'No':0})
df[cols].head()

   Churn
0      0
1      0
2      1
3      0
4      1

In [56]:
# Displaying 0 & 1 instead of yes/no.

df["Churn"].value_counts(normalize=True) *100

Churn
0    73.463013
1    26.536987
Name: proportion, dtype: float64

In [57]:
# rows x columns.

df.shape

(7043, 20)

In [58]:
for col in df.select_dtypes(exclude="number").columns:
    print(col, list(df[col].unique()))

gender ['Female', 'Male']
Partner ['Yes', 'No']
Dependents ['No', 'Yes']
PhoneService ['No', 'Yes']
MultipleLines ['No phone service', 'No', 'Yes']
InternetService ['DSL', 'Fiber optic', 'No']
OnlineSecurity ['No', 'Yes', 'No internet service']
OnlineBackup ['Yes', 'No', 'No internet service']
DeviceProtection ['No', 'Yes', 'No internet service']
TechSupport ['No', 'Yes', 'No internet service']
StreamingTV ['No', 'Yes', 'No internet service']
StreamingMovies ['No', 'Yes', 'No internet service']
Contract ['Month-to-month', 'One year', 'Two year']
PaperlessBilling ['Yes', 'No']
PaymentMethod ['Electronic check', 'Mailed check', 'Bank transfer (automatic)', 'Credit card (automatic)']

In [59]:
# Model understands numbers so I have converted these columns using map.(encoding)

cols = ['Partner','Dependents','PhoneService','PaperlessBilling']

for col in cols:
    df[col] = df[col].map({'Yes': 1, 'No': 0})
df[cols].head()

   Partner  Dependents  PhoneService  PaperlessBilling
0        1           0             0                 1
1        0           0             1                 0
2        0           0             1                 1
3        0           0             0                 0
4        0           0             1                 1

In [60]:
df.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [61]:
# Same converted multiple columns using get_dummies.

df = pd.get_dummies(df,columns=['gender', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaymentMethod'], drop_first=True)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7043 non-null   int64
 1   Partner                                7043 non-null   int64
 2   Dependents                             7043 non-null   int64
 3   tenure                                 7043 non-null   int64
 4   PhoneService                           7043 non-null   int64
 5   PaperlessBilling                       7043 non-null   int64
 6   MonthlyCharges                         7043 non-null   float64
 7   TotalCharges                           7043 non-null   float64
 8   Churn                                  7043 non-null   int64
 9   gender_Male                            7043 non-null   bool
 10  MultipleLines_No phone service         7043 non-null   bool
 11  MultipleLines_Yes                      7043 non-null   bool
 12  InternetService_Fiber optic            7043 non-null   bool
 13  InternetService_No                     7043 non-null   bool
 14  OnlineSecurity_No internet service     7043 non-null   bool
 15  OnlineSecurity_Yes                     7043 non-null   bool
 16  OnlineBackup_No internet service       7043 non-null   bool
 17  OnlineBackup_Yes                       7043 non-null   bool
 18  DeviceProtection_No internet service   7043 non-null   bool
 19  DeviceProtection_Yes                   7043 non-null   bool
 20  TechSupport_No internet service        7043 non-null   bool
 21  TechSupport_Yes                        7043 non-null   bool
 22  StreamingTV_No internet service        7043 non-null   bool
 23  StreamingTV_Yes                        7043 non-null   bool
 24  StreamingMovies_No internet service    7043 non-null   bool
 25  StreamingMovies_Yes                    7043 non-null   bool
 26  Contract_One year                      7043 non-null   bool
 27  Contract_Two year                      7043 non-null   bool
 28  PaymentMethod_Credit card (automatic)  7043 non-null   bool
 29  PaymentMethod_Electronic check         7043 non-null   bool
 30  PaymentMethod_Mailed check             7043 non-null   bool
dtypes: bool(22), float64(2), int64(7)
memory usage: 646.7 KB

In [62]:
# Splitting X & y(Target).

X = df.drop('Churn',axis = 1)
y = df['Churn']

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

Feature shape: (7043, 30)
Target shape: (7043,)

In [63]:
# Training and testing.

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2,random_state = 42,stratify=y)

print("Training state:", X_train.shape)
print("Testing state:", X_test.shape)

Training state: (5634, 30)
Testing state: (1409, 30)

In [64]:
# Training classification model using Logistic regression.

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=10000)

model.fit(X_train,y_train)
print("Model Trained")

Model Trained

In [65]:
# Metrics calculaltion.

from sklearn.metrics import accuracy_score,confusion_matrix, classification_report

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)

#Accuracy sometimes hides problems so confusion matrix was used.

matrix = confusion_matrix(y_test,y_pred)

print("Accuracy_Score:", round(accuracy,2))
print("Confusion Matrix:", matrix)
print(classification_report(y_test, y_pred))

Accuracy_Score: 0.81
Confusion Matrix: [[927 108]
 [165 209]]
              precision    recall  f1-score   support

           0       0.85      0.90      0.87      1035
           1       0.66      0.56      0.60       374

    accuracy                           0.81      1409
   macro avg       0.75      0.73      0.74      1409
weighted avg       0.80      0.81      0.80      1409

In [67]:
# Just using anothere model to see/compare with another model's result.

from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(max_depth = 5, random_state = 42)
tree.fit(X_train , y_train)
tree_pred = tree.predict(X_test)

print("Tree Trained")

Tree Trained

In [68]:
from sklearn.metrics import classification_report

print(classification_report(y_test,tree_pred))

              precision    recall  f1-score   support

           0       0.84      0.89      0.86      1035
           1       0.63      0.54      0.58       374

    accuracy                           0.79      1409
   macro avg       0.74      0.71      0.72      1409
weighted avg       0.79      0.79      0.79      1409

## Project Summary

I built Models to predict whether a Telecom customer will churn or not.(Leave/stay).

## Data
- The dataset has 7043 customers.
- 73.5% of customers stayed and 26.5% left.
- fixed the TotalCharges column, which was stored as text(object) and not numbers.
- changed the text columns into numbers using .map() and get_dummies().

## Models and Results
- Logistic Regression: accuracy: 81% , recall:56%(209/374).
- Decision Tree: accuracy: 79% , recall: 54%.
- The better model was Logistic Regression.

## Key Finding
Accuracy looked good at 81 %, but recall was only 56 %.
This means the model missed almost half of the customers who left.
“This is a problem because the company loses actual customers it could have kept, and keeping a customer costs less than finding a new one."